### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by schignel** [maurodlt/SciKGraph#1]
Hello, I'm trying to follow the instructions for installing and running the software, but I don't understand what to do for these steps:

Install ScikGrapp-App: pip3 install scikgraph

Install server: sudo apt install python3-waitress

Run: waitress-serve --call 'scikgraph:create_app'

**Comment by maurodlt** [comment]
Hello @schignel,

I thought I made SciKGraph available on PyPI, which does not seem to be the case...

I will upload it on PyPi and update the installation instructions accordingly : )

**Comment by maurodlt** [comment]
Hi @schignel,

I just uploaded ScikGraph to PyPi, now you can install it following the installation tutorial.

Installation: (You shall install Cytoscape as well)
`pip3 install scikgraph`
`sudo apt install python3-waitress`

Running:
`sudo /usr/local/src/cytoscape-3.7.2/cytoscape.sh`
`waitress-serve --call 'scikgraph:create_app'`

**Comment by schignel** [comment]
Thanks! I was able to install Cytoscape and scikgraph. However, when I run the command "sudo apt install python3-waitress" I get an error saying 'sudo' is not recognized...

Can you provide a little more detail in how to get the program running (I'm on Windows 10)

**Comment by maurodlt** [comment]
Hello @schignel,

Unfortunately, I never tried to run Scikgraph on Windows so I cannot give proper support for it.
You should be able to install waitress via pip on windows as well `pip install waitress`.
However, I do not know the exact steps to run waitress via windows after its installation... Moreover, there should be some commands inside Scikgraph that are Unix specific. Again, as I have never tried to run it on Windows I do not know where it might break.

**Comment by schignel** [comment]
Thanks @maurodlt, I'll think about getting a unix machine and trying it out.
